config/routes.rb
Rails.application.routes.draw do

  resources :invoices

  resources :notes,except:[:edit, :new]

  resources :patients do
    resources :appointment_schedules
  end

  resources :appointment_schedules do
    resources :notes
  end

  resources :diagnostic_codes do
    member do
      get :get_price
    end
  end

  resources :physicians do
    resources :appointment_schedules, only:[:index,:show,:edit]
  end

  get 'home/index'
  root :to=> "home#index"

  get "/admin" ,to: "home#admin"
  get "/physician_page",to: "home#physician"
  get "/office_worker",to: "home#office_worker"
  get "/patient_page",to: "home#patient"

  get "/report" ,to: "home#report"
  post "/search" ,to: "home#report"
  get "/get_time_available", to: "appointment_schedules#get_time_available"

  get "/invoice" , to: "home#invoice"

end

app/models/diagnostic_code.rb
class DiagnosticCode < ActiveRecord::Base
  has_many :appointment_schedules
  has_many :invoices

  validates_presence_of :name
  validates_presence_of :price, :greater_than => 0
  validates_uniqueness_of :code

  def to_s
    "#{code} #{name}"
  end
end

app/controllers/diagnostic_codes_controller.rb
class DiagnosticCodesController < ApplicationController
  before_action :set_diagnostic_code, :only=> [:show, :edit, :update, :destroy,:get_price]

  # GET /diagnostic_codes
  # GET /diagnostic_codes.json
  def index
    @diagnostic_codes = DiagnosticCode.all.order("code ASC").paginate(:page=>params[:page], :per_page=>15)
  end

  # GET /diagnostic_codes/1
  # GET /diagnostic_codes/1.json
  def show
  end

  # GET /diagnostic_codes/new
  def new
    @diagnostic_code = DiagnosticCode.new
  end

  # GET /diagnostic_codes/1/edit
  def edit
  end

  # POST /diagnostic_codes
  # POST /diagnostic_codes.json
  def create
    @diagnostic_code = DiagnosticCode.new(diagnostic_code_params)

    respond_to do |format|
      if @diagnostic_code.save
        format.html { redirect_to @diagnostic_code, notice: 'Diagnostic code was successfully created.' }
        format.json { render :show, status: :created, location: @diagnostic_code }
      else
        format.html { render :new }
        format.json { render json: @diagnostic_code.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /diagnostic_codes/1
  # PATCH/PUT /diagnostic_codes/1.json
  def update
    respond_to do |format|
      if @diagnostic_code.update(diagnostic_code_params)
        format.html { redirect_to @diagnostic_code, notice: 'Diagnostic code was successfully updated.' }
        format.json { render :show, status: :ok, location: @diagnostic_code }
      else
        format.html { render :edit }
        format.json { render json: @diagnostic_code.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /diagnostic_codes/1
  # DELETE /diagnostic_codes/1.json
  def destroy
    @diagnostic_code.destroy
    respond_to do |format|
      format.html { redirect_to diagnostic_codes_url, notice: 'Diagnostic code was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def get_price

  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_diagnostic_code
    @diagnostic_code = DiagnosticCode.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def diagnostic_code_params
    params.require(:diagnostic_code).permit(:name, :price, :code)
  end
end

app/helpers/diagnostic_codes_helper.rb
module DiagnosticCodesHelper
end

app/views/diagnostic_codes/_form.html.erb
<%= form_for(@diagnostic_code ,{:class=>"form-control"}) do |f| %>
    <% if @diagnostic_code.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@diagnostic_code.errors.count, "error") %> prohibited this diagnostic_code from being saved:</h2>

          <ul>
            <% @diagnostic_code.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field-control">
      <%= f.label :code,:class=>"label-control" %><br>
      <%= f.text_field :code,:class=>"form-control", :require=>true%>
    </div>
    <div class="field-control">
      <%= f.label :name,:class=>"label-control" %><br>
      <%= f.text_field :name,:class=>"form-control", :require=>true%>
    </div>
    <div class="field-control ">
      <%= f.label :price,:class=>"label-control" %><br>
      <%= f.text_field :price ,:class=>"form-control", :require=>true%>
    </div>
    <div class="actions">
      <%= f.submit :class=>"btn btn-success"%>
    </div>
<% end %>

app/views/diagnostic_codes/edit.html.erb
<div class="col-lg-12">
  <h1>Editing Diagnostic Code</h1>

  <%= render 'form' %>

  <%= link_to 'Show', @diagnostic_code , :class=>'btn btn-info' %>
  <%= link_to 'Back', diagnostic_codes_path, :class=>'btn btn-warning'  %>
</div>

app/views/diagnostic_codes/get_price.js.erb
$( "#invoice_price").val("<%= "#{@diagnostic_code.price}" %>");

app/views/diagnostic_codes/index.html.erb
<div class="col-lg-12">  <%= link_to 'New Diagnostic code', new_diagnostic_code_path,:class => "btn btn-success" %>
  <h1>Listing Diagnostic Codes</h1>

  <table class="table">
    <thead>
    <tr>
      <th>Diagnostic Code</th>
      <th>Name</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @diagnostic_codes.each do |diagnostic_code| %>
        <tr>
          <td><%= diagnostic_code.code %></td>
          <td><%= diagnostic_code.name %></td>
          <td><%= diagnostic_code.price %></td>
          <td><%= link_to 'Show', diagnostic_code,:class => "btn btn-info" %></td>
          <td><%= link_to 'Edit', edit_diagnostic_code_path(diagnostic_code),:class => "btn btn-primary" %></td>
          <td><%= link_to 'Destroy', diagnostic_code, method: :delete, data: { confirm: 'Are you sure?' },:class => "btn btn-danger" %></td>
        </tr>
    <% end %>
    </tbody>
  </table>
  <%= will_paginate @diagnostic_codes %>
  <br>


</div>

app/views/diagnostic_codes/new.html.erb
<div class="col-lg-10">
  <h1>New Diagnostic Code</h1>

  <%= render 'form' %>

  <%= link_to 'Back', diagnostic_codes_path,class: 'btn btn-warning' %>
</div>

app/views/diagnostic_codes/show.html.erb
<p>
  <strong>Code:</strong>
  <%= @diagnostic_code.code %>
</p>
<p>
  <strong>Name:</strong>
  <%= @diagnostic_code.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @diagnostic_code.price %>
</p>

<%= link_to 'Edit', edit_diagnostic_code_path(@diagnostic_code) , :class=>'btn btn-info' %>
<%= link_to 'Back', diagnostic_codes_path, :class=>'btn btn-warning' %>