config/routes.rb
Rails.application.routes.draw do

  resources :invoices

  resources :notes,except:[:edit, :new]

  resources :patients do
    resources :appointment_schedules
  end

  resources :appointment_schedules do
    resources :notes
  end

  resources :diagnostic_codes do
    member do
      get :get_price
    end
  end

  resources :physicians do
    resources :appointment_schedules, only:[:index,:show,:edit]
  end

  get 'home/index'
  root :to=> "home#index"

  get "/admin" ,to: "home#admin"
  get "/physician_page",to: "home#physician"
  get "/office_worker",to: "home#office_worker"
  get "/patient_page",to: "home#patient"

  get "/report" ,to: "home#report"
  post "/search" ,to: "home#report"
  get "/get_time_available", to: "appointment_schedules#get_time_available"

  get "/invoice" , to: "home#invoice"

end

app/models/patient.rb
class Patient < ActiveRecord::Base
  validates_presence_of :first_name
  validates_presence_of :last_name

  has_many :appointment_schedules

  has_many :invoice
  belongs_to :physician

  def name
    "#{first_name} #{last_name}"
  end
  def to_s
    name
  end

end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update, :destroy]

  # GET /patients
  # GET /patients.json
  def index
    @patients = Patient.order("lower(first_name) ASC").paginate(:page=>params[:page], :per_page=>15)
  end

  # GET /patients/1
  # GET /patients/1.json
  def show
  end

  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients
  # POST /patients.json
  def create
    @patient = Patient.new(patient_params)
    respond_to do |format|
      if @patient.save
        format.html { redirect_to @patient, notice: 'Patient was successfully created.' }
        format.json { render :show, status: :created, location: @patient }
      else
        format.html { render :new }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1
  # PATCH/PUT /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to @patient, notice: 'Patient was successfully updated.' }
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :edit }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1
  # DELETE /patients/1.json
  def destroy
    @patient.destroy
    respond_to do |format|
      format.html { redirect_to patients_url, notice: 'Patient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_patient
    @patient = Patient.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def patient_params
    params.require(:patient).permit(:first_name, :last_name, :date_of_birth, :address, :phone, :email)
  end
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/patients/_form.html.erb
<%= form_for(@patient,{:class=>"form-control"}) do |f| %>
    <% if @patient.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

          <ul>
            <% @patient.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field-control">
      <%= f.label :first_name ,:class=>"label-control" %><br>
      <%= f.text_field :first_name  ,:class=>"form-control"%>
    </div>
    <div class="field-control">
      <%= f.label :last_name ,:class=>"label-control" %><br>
      <%= f.text_field :last_name  ,:class=>"form-control"%>
    </div>
    <div class="field-control">
      <%= f.label :date_of_birth,:class=>"label-control" %><br>
      <%= f.text_field :date_of_birth  ,:class=>"form-control"%>
    </div>
    <div class="field-control">
      <%= f.label :address,:class=>"label-control" %><br>
      <%= f.text_area :address  ,:class=>"form-control"%>
    </div>
    <div class="field-control">
      <%= f.label :phone ,:class=>"label-control" %><br>
      <%= f.text_field :phone  ,:class=>"form-control"%>
    </div>
    <div class="field-control">
      <%= f.label :email ,:class=>"label-control" %><br>
      <%= f.text_field :email,:class=>"form-control"%>
    </div>
    <div class="actions">
      <%= f.submit  :class=>"btn btn-success"%>
    </div>
<% end %>
<script>
    $(function() {
        $( "#patient_date_of_birth" ).datepicker({ dateFormat: 'yy-mm-dd' });
    });
</script>

app/views/patients/edit.html.erb
<div class="col-lg-12">
  <h1>Editing patient</h1>

  <%= render 'form' %>

  <%= link_to 'Show', @patient ,:class=>"btn btn-info" %>
  <%= link_to 'Back', patients_path ,:class=>"btn btn-warning" %>
</div>

app/views/patients/index.html.erb
<div class="col-lg-12">
  <h1>Listing Patients</h1>

  <table class="table">
    <thead>
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Date of Birth</th>
      <th>Address</th>
      <th>Phone</th>
      <th>E-Mail</th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @patients.each do |patient| %>
        <tr>
          <td><%= patient.first_name %></td>
          <td><%= patient.last_name %></td>
          <td><%= patient.date_of_birth %></td>
          <td><%= patient.address %></td>
          <td><%= patient.phone %></td>
          <td><%= patient.email %></td>
          <td><%= link_to 'Add/View Appointment', patient ,:class=>"btn btn-info"%></td>
          <td><%= link_to 'Edit', edit_patient_path(patient),:class=>"btn btn-primary"%></td>
          <td><%= link_to 'Destroy', patient, method: :delete, data: { confirm: 'Are you sure?' } ,:class=>"btn btn-danger"%></td>
        </tr>
    <% end %>
    </tbody>
  </table>

  <br>

  <%= will_paginate @patients %>
</div>

app/views/patients/new.html.erb
<div class="col-lg-12">
  <h1>New Patient Form</h1>

  <%= render 'form' %>

  <%= link_to 'Back', patients_path ,:class=>"btn btn-warning" %>
</div>

app/views/patients/show.html.erb
<div class="col-lg-12">


  <p>
    <strong>First Name:</strong>
    <%= @patient.first_name %>
  </p>

  <p>
    <strong>Last Name:</strong>
    <%= @patient.last_name %>
  </p>

  <p>
    <strong>Date of Birth:</strong>
    <%= @patient.date_of_birth %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= @patient.address %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= @patient.phone %>
  </p>

  <p>
    <strong>E-Mail:</strong>
    <%= @patient.email %>
  </p>
  <%= link_to 'All Appointments', patient_appointment_schedules_path(@patient)  ,:class=>"btn btn-info" %>
  <%= link_to 'New Appointment', new_patient_appointment_schedule_path(@patient)  ,:class=>"btn btn-info" %>
  <%= link_to 'Edit', edit_patient_path(@patient) ,:class=>"btn btn-primary" %>
  <%= link_to 'Back', patients_path ,:class=>"btn btn-warning" %>
</div>