config/routes.rb
Rails.application.routes.draw do

  resources :invoices

  resources :notes,except:[:edit, :new]

  resources :patients do
    resources :appointment_schedules
  end

  resources :appointment_schedules do
    resources :notes
  end

  resources :diagnostic_codes do
    member do
      get :get_price
    end
  end

  resources :physicians do
    resources :appointment_schedules, only:[:index,:show,:edit]
  end

  get 'home/index'
  root :to=> "home#index"

  get "/admin" ,to: "home#admin"
  get "/physician_page",to: "home#physician"
  get "/office_worker",to: "home#office_worker"
  get "/patient_page",to: "home#patient"

  get "/report" ,to: "home#report"
  post "/search" ,to: "home#report"
  get "/get_time_available", to: "appointment_schedules#get_time_available"

  get "/invoice" , to: "home#invoice"

end

app/models/appointment_schedule.rb
class AppointmentSchedule < ActiveRecord::Base
  validates_presence_of :patient_id
  validates_presence_of :physician_id

  validates_presence_of :date_rdv
  validates_presence_of :hour_rdv

  validate :valid_date?



  has_many :notes
  belongs_to :diagnostic_code
  belongs_to :patient
  belongs_to :physician
  has_many :invoices

  Time_Work= [
      "08:00 AM", "08:30 AM", "09:00 AM", "09:30 AM",
      "10:00 AM", "10:30 AM", "11:00 AM", "11:30 AM",
      "12:00 PM", "12:30 PM", "01:00 PM", "01:30 PM",
      "02:00 PM", "02:30 PM", "03:00 PM", "03:30 PM",
      "04:00 PM" ]

  def valid_date?

    if Date.today > self.date_rdv
      errors.add :base, "Invalid date: date is prior than today."
    end
    day = self.date_rdv.strftime("%A")
    if ["Saturday", "Sunday"].include?(day.capitalize)
      errors.add :base, "Invalid date: cannot make an appointment on the weekend."
    end
  end

  def time_appointment
    "The #{date_rdv} at #{hour_rdv}"
  end

  def to_s
    "#{patient}: #{time_appointment} "
  end
end

app/controllers/appointment_schedules_controller.rb
class AppointmentSchedulesController < ApplicationController
  include ApplicationHelper
  before_action :set_rdv, only: [:show, :edit, :update, :destroy]

  before_action :set_date, only: [:create, :update]
  # GET /rdvs
  # GET /rdvs.json
  def index
    patient_id = params[:patient_id]
    if patient_id
      @appointment_schedules = AppointmentSchedule.where(patient_id: patient_id).order("date_rdv DESC ,hour_rdv DESC").paginate(:page=>params[:page], :per_page=>15)
    else
      physician_id = params[:physician_id]
      if physician_id
        @appointment_schedules = AppointmentSchedule.where(physician_id: physician_id).order("date_rdv DESC, hour_rdv DESC").paginate(:page=>params[:page], :per_page=>15)
      else
        @appointment_schedules = AppointmentSchedule.all.order("date_rdv DESC, hour_rdv DESC").paginate(:page=>params[:page], :per_page=>15)
      end
    end

  end

  def get_time_available
    date = params[:date_rdv]
    phys = params[:physician_id]
    return if date.blank?
    if phys and phys.present?
      rdvs = AppointmentSchedule.where(date_rdv: date).where(physician_id: phys).map(&:hour_rdv)
    else
      rdvs = AppointmentSchedule.where(date_rdv: date).map(&:hour_rdv)
    end

    @time = AppointmentSchedule::Time_Work
    @times= @time.select{|time| !rdvs.include?(time)}
  end

  # GET /rdvs/1
  # GET /rdvs/1.json
  def show
  end

  # GET /rdvs/new
  def new
    patient = params[:patient_id]
    @appointment_schedule = AppointmentSchedule.new(patient_id: patient)
  end

  # GET /rdvs/1/edit
  def edit
    rdvs = AppointmentSchedule.where(date_rdv: @appointment_schedule.date_rdv).where("id != ?", @appointment_schedule.id).map(&:hour_rdv)
    @times= AppointmentSchedule::Time_Work
    @times.reject!{|time| rdvs.include?(time)}
  end

  # POST /rdvs
  # POST /rdvs.json
  def create
    @appointment_schedule = AppointmentSchedule.new(rdv_params)

    respond_to do |format|
      if @appointment_schedule.save
        format.html { redirect_to patient_appointment_schedule_path(@appointment_schedule.patient_id, @appointment_schedule), notice: 'Appointment was successfully created.' }
        format.json { render :show, status: :created, location: @appointment_schedule }
      else
        format.html { render :new }
        format.json { render json: @appointment_schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rdvs/1
  # PATCH/PUT /rdvs/1.json
  def update

    params[:appointment_schedule][:hour_rdv] = @appointment_schedule.hour_rdv if params[:appointment_schedule][:hour_rdv].nil? or params[:appointment_schedule][:hour_rdv].blank?
    respond_to do |format|
      if @appointment_schedule.update(rdv_params)
        format.html { redirect_to patient_appointment_schedule_path(@appointment_schedule.patient_id, @appointment_schedule), notice: 'Appointment was successfully updated.' }
        format.json { render :show, status: :ok, location: @appointment_schedule }
      else
        format.html { rdvs = AppointmentSchedule.where(date_rdv: @appointment_schedule.date_rdv).where("id != ?", @appointment_schedule.id).map(&:hour_rdv)
        @times= AppointmentSchedule::Time_Work
        @times.reject!{|time| rdvs.include?(time)}
        render :edit }
        format.json { render json: @appointment_schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rdvs/1
  # DELETE /rdvs/1.json
  def destroy
    if Date.today != @appointment_schedule.date_rdv or (@appointment_schedule.hour_rdv.to_datetime - Time.now)>8.hours
      @appointment_schedule.destroy
      respond_to do |format|
        format.html { redirect_to patient_path(params[:patient_id]), notice: 'Appointment was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html {
          flash[:error] = "Cannot cancel this appointment because it's for #{@appointment_schedule.hour_rdv - Time.now}"
          redirect_to :back
        }
        format.json { head :no_content }
      end
    end

  end
  private
  # Use callbacks to share common setup or constraints between actions.
  def set_rdv
    @appointment_schedule = AppointmentSchedule.find(params[:id])
  end

  def set_date
    date = params[:appointment_schedule][:date_rdv]
    params[:appointment_schedule][:date_rdv] = convert_to_date(date)
    params[:appointment_schedule][:hour_rdv] = params[:appointment_schedule_hour_rdv] if params[:appointment_schedule][:hour_rdv].blank?
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def rdv_params
    params.require(:appointment_schedule).permit(:patient_id,:physician_id, :date_rdv, :hour_rdv, :reason, :diagnostic_code_id)
  end
end

app/helpers/appointment_schedules_helper.rb
module AppointmentSchedulesHelper
end

app/views/appointment_schedules/_form.html.erb
<%= form_for(@appointment_schedule,{:class=>"form-control"}) do |f| %>
    <% if @appointment_schedule.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@appointment_schedule.errors.count, "error") %> prohibited this appointment_schedule from being saved:</h2>

          <ul>
            <% @appointment_schedule.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <%= f.hidden_field :patient_id %>
    <% if params[:physician_id] %>
        <div class="field-control" style="display: none;">
    <% else %>
        <div class="field-control">
    <% end %>
    <%= f.label :physician_id ,:class=>"label-control" %><br>
    <%= f.select( :physician_id,options_for_select(Physician.all.map{|phys| [ phys.name,phys.id]},@appointment_schedule.physician_id ),:include_blank=> true)%>
    </div>
    <% if params[:physician_id] %>
        <div class="field-control" style="display: none;">
    <% else %>
        <div class="field-control">
    <% end %>
    <%= f.label :date ,:class=>"label-control" %><br>
    <%= f.text_field :date_rdv, :require=>true%>
    </div>
    <div class="field-control" id="time_work"> </div>

    <% unless params[:action] == "new" %>
        <div class="field-control">
          <%= f.label :diagnostic_code_id ,:class=>"label-control" %><br>
          <%= f.select(:diagnostic_code_id,options_for_select(DiagnosticCode.all.order("name ASC").map{|code| [ "#{code.code}: #{code.name}",code.id]},@appointment_schedule.diagnostic_code_id ),:include_blank=> true) %>
        </div>
    <% end %>
    <% if params[:physician_id] %>
        <div class="field-control" style="display: none;">
    <% else %>
        <div class="field-control">

    <% end %>

    <%= f.label :reason ,:class=>"label-control" %><br>
    <%= f.text_field :reason ,:class=>"form-control" %>
    </div>

    <div class="actions" >
      <%= f.submit "Submit",:class=>"btn btn-success" %>
    </div>
<% end %>
<script>
    $(function() {
        $( "#appointment_schedule_date_rdv" ).datepicker({ dateFormat: 'yy-mm-dd' });
    });
    $(document).ready(function(){
        $( "#appointment_schedule_date_rdv").on('change',function(e){
            date = $( "#appointment_schedule_date_rdv").val();
            phys = $( "#appointment_schedule_physician_id").val();
            $.getScript('/get_time_available.js?date_rdv='+date+'&physician_id='+phys);
        });
        $( "#appointment_schedule_physician_id").on('change',function(e){
            date = $( "#appointment_schedule_date_rdv").val();
            phys = $( "#appointment_schedule_physician_id").val();
            $.getScript('/get_time_available.js?date_rdv='+date+'&physician_id='+phys);
        });

    });
</script>

app/views/appointment_schedules/_time_work.html.erb
<%= label_tag :Appointment_Time  %><br>
<%= select_tag( :appointment_schedule_hour_rdv,options_for_select(@times.map{|time| [ time,time]}),{:class=>"form-control"}) %>

app/views/appointment_schedules/edit.html.erb
<div class="col-lg-12">
  <% if params[:physician_id] %>
      <h1>Assign Diagnostic code</h1>
  <% else %>
      <h1>Editing appointment</h1>
  <% end %>
  <%= render 'form' %>

  <%= link_to 'Show', @appointment_schedule ,:class=>"btn btn-info" %>
  <%= link_to 'Back', appointment_schedules_path,:class=>"btn btn-warning" %>
</div>

app/views/appointment_schedules/get_time_available.js.erb
<% if @times %>
$("#time_work").html("<%= escape_javascript(render partial: 'appointment_schedules/time_work') %>");
<% end %>

app/views/appointment_schedules/index.html.erb
<div class="col-lg-12">
  <% if params[:patient_id] %>
      <%= link_to 'New Appointment', new_patient_appointment_schedule_path(params[:patient_id])  ,:class=>"btn btn-info" %>
  <% end %>
  <h1>Listing Appointments</h1>

  <table class="table">
    <thead>
    <tr>
      <% if params[:physician_id] %>
          <th>Patient</th>
      <% end %>
      <% if params[:patient_id] %>
          <th>Physician</th>
      <% end %>
      <th>Appointment Date</th>
      <th>Appointment Time</th>
      <th>Reason</th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @appointment_schedules.each do |rdv| %>
        <tr>
          <% if params[:physician_id] %>
              <th><%= rdv.patient %></th>
          <% end %>
          <% if params[:patient_id] %>
              <th><%= rdv.physician %></th>
          <% end %>
          <td><%= rdv.date_rdv %></td>
          <td><%= rdv.hour_rdv %></td>
          <td><%= rdv.reason %></td>
          <% if params[:physician_id] %>

              <td><%= link_to 'Show', physician_appointment_schedule_path(rdv.physician,rdv),:class => "btn btn-info" %></td>
              <% if rdv.diagnostic_code_id %>
                  <td><%= link_to 'Re-assign Diagnostic code', edit_physician_appointment_schedule_path(rdv.physician,rdv) ,:class => "btn btn-info" %></td>
              <% else %>
                  <td><%= link_to 'Assign Diagnostic code', edit_physician_appointment_schedule_path(rdv.physician,rdv) ,:class => "btn btn-primary" %></td>
              <% end %>
              <td><%= link_to 'Give notes', new_appointment_schedule_note_path(rdv),:class => "btn btn-info" %></td>
          <% else %>
              <td><%= link_to 'Show', patient_appointment_schedule_path(rdv.patient,rdv),:class => "btn btn-info" %></td>
              <td><%= link_to 'Edit', edit_patient_appointment_schedule_path(rdv.patient,rdv) ,:class => "btn btn-primary" %></td>
              <td><%= link_to 'Cancel Appointment', patient_appointment_schedule_path(rdv.patient,rdv), method: :delete, data: { confirm: 'Are you sure?' } ,:class => "btn btn-danger" %></td>
          <% end %>
        </tr>
    <% end %>
    </tbody>
  </table>


  <br>
  <%= will_paginate @appointment_schedules %>
</div>

app/views/appointment_schedules/new.html.erb
<div class="col-lg-12">
  <h1>New Appointment</h1>

  <%= render 'form' %>

  <%= link_to 'Back', appointment_schedules_path ,:class => "btn btn-warning" %>
</div>

app/views/appointment_schedules/show.html.erb
<h3><%= link_to "Patient information:", patient_path(@appointment_schedule.patient) %></h3>
<p>
  <%=  @appointment_schedule.patient  %>
</p>
<h3> Appointment Schedule Information:</h3>
<p>
  <strong>Appointment Date:</strong>
  <%= @appointment_schedule.date_rdv %>
</p>

<p>
  <strong>Appointment Time:</strong>
  <%= @appointment_schedule.hour_rdv %>
</p>

<p>
  <strong>Reason:</strong>
  <%= @appointment_schedule.reason || 'N/A' %>
</p>
<%  if @appointment_schedule.notes and @appointment_schedule.notes.present? %>
    <h1> Notes:</h1>
    <ul>
      <% @appointment_schedule.notes.each do |note| %>
          <li>
            <%= note.note %>
          </li>
      <% end%>
    </ul>
<% end %>
<%= link_to 'Edit', edit_appointment_schedule_path(@appointment_schedule) ,:class=>"btn btn-primary" %>
<%= link_to 'Back', appointment_schedules_path ,:class=>"btn btn-warning" %>