config/routes.rb
Rails.application.routes.draw do

  resources :invoices

  resources :notes,except:[:edit, :new]

  resources :patients do
    resources :appointment_schedules
  end

  resources :appointment_schedules do
    resources :notes
  end

  resources :diagnostic_codes do
    member do
      get :get_price
    end
  end

  resources :physicians do
    resources :appointment_schedules, only:[:index,:show,:edit]
  end

  get 'home/index'
  root :to=> "home#index"

  get "/admin" ,to: "home#admin"
  get "/physician_page",to: "home#physician"
  get "/office_worker",to: "home#office_worker"
  get "/patient_page",to: "home#patient"

  get "/report" ,to: "home#report"
  post "/search" ,to: "home#report"
  get "/get_time_available", to: "appointment_schedules#get_time_available"

  get "/invoice" , to: "home#invoice"

end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Home" , root_path, class:"navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Admin <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to " Add Physician", physicians_path %></li>
            <li><%= link_to " Add Diagnostic Codes", diagnostic_codes_path %></li>
            <li class="divider"></li>
            <li><%= link_to "Report", "/report" %></li>
          </ul>
        </li>
      </ul>

      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Office Worker <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to "Generate Invoice", new_invoice_path %></li>
            <li class="divider"></li>
            <li><%= link_to "Invoices", invoices_path %></li>

          </ul>
        </li>
      </ul>

      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"> Physician <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <% Physician.order("name asc").each do |phys| %>
                <li><%= link_to phys.name , physician_appointment_schedules_path(phys) %></li>
            <% end %>
          </ul>
        </li>
      </ul>

      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Patient <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to "New Patient Form", new_patient_path %></li>
            <li class="divider"></li>
            <li><%= link_to "Add Appointment", patients_path %></li>
          </ul>
        </li>
      </ul>




    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Appointment Application</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">

  <%= render partial: 'layouts/navigation' %>
  <% flash.each do |type, message| %>
      <div class="alert <%= type %>">
        <button class="close" data-dismiss="alert">×</button>
        <%= message %>
      </div>
  <% end %>
  <%= yield %>
</div>
</body>
</html>